[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = direct
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    adafruit/Adafruit MLX90614 Library
    adafruit/Adafruit BusIO
    blynkkk/Blynk@^1.3.2